language: cpp
# install dependencies
install:
    - "sudo apt-add-repository -y \"deb http://ubuntu.mirror.cambrium.nl/ubuntu/ quantal main\""
    - "sudo apt-get update"
    - "sudo apt-get install gcc g++ build-essential" # python3-dev"
# check submodules are available
before_script:
   - "git submodule update --init"
   - "gcc --version"
script:
   - "cmake ."
   - "make"

notifications:
  irc: "irc.freenode.net#0x10c-galaxy"
